import '../../resources/manager_strings.dart';

const Map<String, String> ar = {
  'english': 'انجليزي',
  'Sign up': 'تسجيل حساب جديد',
  ManagerStrings.email: 'الإيميل',
  ManagerStrings.userDataSaved: 'تم حفظ بيانات المستخدم',
  ManagerStrings.noDataFound: 'لا توجد بيانات',
  ManagerStrings.userName: 'اسم المستخدم',
  ManagerStrings.save: 'حفظ',
  ManagerStrings.send: 'إرسال',
  ManagerStrings.suggestion: 'اقتراح',
  ManagerStrings.message: 'رسالة',
  ManagerStrings.phone: 'رقم الهاتف',
  ManagerStrings.phoneDot: 'رقم الهاتف:',
  ManagerStrings.name: 'الاسم',
  ManagerStrings.password: 'كلمة المرور',
  ManagerStrings.forgetPassword: 'نسيت كلمة المرور',
  ManagerStrings.title: 'عنوان',
  ManagerStrings.total: 'المجموع:',
  ManagerStrings.home: 'الصفحة الرئيسية',
  ManagerStrings.signIn: 'تسجيل الدخول',
  ManagerStrings.vegetables: 'خضروات',
  ManagerStrings.fruits: 'فواكه',
  ManagerStrings.meat: 'لحوم',
  ManagerStrings.menu: 'القائمة',
  ManagerStrings.myOrder: 'طلبي',
  ManagerStrings.myCart: 'عربة التسوق',
  ManagerStrings.offers: 'العروض',
  ManagerStrings.changeLanguages: 'تغيير اللغة',
  ManagerStrings.changePassword: 'تغيير كلمة المرور',
  ManagerStrings.changeCountry: 'تغيير الدولة',
  ManagerStrings.aboutUs: 'معلومات عنا',
  ManagerStrings.contactUs: 'اتصل بنا',
  ManagerStrings.shareApp: 'مشاركة التطبيق',
  ManagerStrings.faq: 'الأسئلة الشائعة',
  ManagerStrings.termsOfUser: 'شروط الاستخدام',
  ManagerStrings.privacyPolicy: 'سياسة الخصوصية',
  ManagerStrings.logOut: 'تسجيل الخروج',
  ManagerStrings.papers: 'الأوراق',
  ManagerStrings.welcome: 'مرحبًا',
  ManagerStrings.thanks: 'شكرًا لك على التسجيل مع تطبيق ال Express',
  ManagerStrings.editProfile: 'تعديل الملف الشخصي',
  ManagerStrings.addToCart: 'أضف إلى السلة',
  ManagerStrings.countInCart: 'عدد العناصر في السلة',
  ManagerStrings.creatingAccount: 'إنشاء حساب...',
  ManagerStrings.openOrder: 'طلب مفتوح',
  ManagerStrings.completedOrder: 'طلب مكتمل',
  ManagerStrings.orderId: 'رقم الطلب:',
  ManagerStrings.product: 'المنتج',
  ManagerStrings.orderDetails: 'تفاصيل الطلب',
  ManagerStrings.quantity: 'الكمية',
  ManagerStrings.apple: 'تفاح',
  ManagerStrings.contactForm: 'نموذج الاتصال',
  ManagerStrings.onDelivery: 'عند التسليم',
  ManagerStrings.address: 'العنوان:',
  ManagerStrings.poweredByHEXA: 'بتصميم HEXA',
  ManagerStrings.contactInfo: 'معلومات التواصل',
  ManagerStrings.doNotHaveAccount: 'ليس لديك حساب؟',
  ManagerStrings.termsAndPrivacy: 'أوافق على الشروط وسياسة الخصوصية',
  ManagerStrings.signUp: 'إنشاء حساب',
  ManagerStrings.signupFailed: 'فشل إنشاء الحساب',
  ManagerStrings.emailCantBeEmpty: 'البريد الإلكتروني لا يمكن أن يكون فارغًا',
  ManagerStrings.dataCantBeEmpty: 'لا يمكن ترك الحقول فارغة',
  ManagerStrings.passwordCantBeEmpty: 'لا يمكن أن تكون كلمة المرور فارغة',
  ManagerStrings.shortPassword: 'كلمة المرور قصيرة جدًا',
  ManagerStrings.invalidPassword: 'كلمة المرور غير صالحة',
  ManagerStrings.invalidEmail: 'بريد إلكتروني غير صالح',
  ManagerStrings.invalidMobileNumber: 'رقم هاتف غير صالح',
  ManagerStrings.mismatchedPassword: 'كلمات المرور غير متطابقة',
  ManagerStrings.signUpDone: 'تم إنشاء الحساب بنجاح',
  ManagerStrings.signInDone: 'تم تسجيل الدخول بنجاح',
  ManagerStrings.termsAndConditions: 'الشروط والأحكام',
  ManagerStrings.outBoardingTitle1: 'ابحث عن مكان عمل مريح 1',
  ManagerStrings.outBoardingTitle2: 'ابحث عن مكان عمل مريح 2',
  ManagerStrings.outBoardingTitle3: 'ابحث عن مكان عمل مريح 3',
  ManagerStrings.outBoardingSubTitle1:
      'نص عشوائي يمكن استخدامه في المقدمة العاطفية 1',
  ManagerStrings.outBoardingSubTitle2:
      'نص عشوائي يمكن استخدامه في المقدمة العاطفية 2',
  ManagerStrings.outBoardingSubTitle3:
      'نص عشوائي يمكن استخدامه في المقدمة العاطفية 3',
  ManagerStrings.getStartButton: 'لنبدأ',
  ManagerStrings.en: 'en',
  ManagerStrings.ar: 'ar',
};
// lanaguage in arabic
